# Climate Credit Risk & Systemic Contagion Model
# Copyright (c) 2026 Mohibul Hoque
# Email: hokworks@gmail.com
# LinkedIn: linkedin.com/in/speedymohibul
# License: MIT License

import os
import json
import numpy as np
import pandas as pd
from data_engine import (
    fetch_or_generate_market_data,
    generate_ngfs_scenarios,
    get_company_financials,
    get_historical_defaults_data,
    get_banking_network
)
from carbon_beta import calculate_tvs
from survival_model import generate_training_cohort, fit_survival_model, predict_probabilities
from scenarios import run_scenario_simulation, analyze_scenario_impact

def main():
    print("Exporting model parameters for the web app...")
    
    # 1. Load baseline data
    market_df = fetch_or_generate_market_data()
    baseline_fin = get_company_financials()
    network_dict = get_banking_network()
    
    # 2. Fit CPH model
    tvs_results = calculate_tvs(market_df)
    cohort = generate_training_cohort(tvs_results, baseline_fin)
    cph = fit_survival_model(cohort)
    
    # 3. Extract baseline survival function
    # Index is time (years), values are baseline S0(t)
    baseline_survival = cph.baseline_survival_
    baseline_survival_dict = {float(t): float(val) for t, val in zip(baseline_survival.index, baseline_survival.iloc[:, 0])}
    
    # 4. Extract CPH coefficients
    coef_dict = {str(cov): float(val) for cov, val in cph.params_.items()}
    
    # 5. Extract company financials
    financials_dict = baseline_fin.to_dict(orient="index")
    
    # 6. Extract TVS scores
    tvs_dict = tvs_results.to_dict(orient="index")
    
    # 7. Extract banking network
    banks_dict = network_dict["banks"].to_dict(orient="index")
    exposures_dict = network_dict["exposures"].to_dict(orient="index")
    interbank_dict = network_dict["interbank"].to_dict(orient="index")
    
    # 8. Extract historical defaults
    hist_defaults = get_historical_defaults_data().to_dict(orient="index")
    
    # 9. Extract scenarios
    scenarios_df = generate_ngfs_scenarios()
    sim_results = run_scenario_simulation(cph, tvs_results, baseline_fin, network_dict, scenarios_df)
    
    # Convert simulation results to JSON-serializable structure
    serializable_sim = {}
    for sc_name, df in sim_results.items():
        # Group by entity type for cleaner rendering
        records = []
        for _, row in df.iterrows():
            record = row.to_dict()
            # Convert timestamp to string if it is a Timestamp
            if isinstance(record.get("Quarter"), pd.Timestamp) or hasattr(record.get("Quarter"), "strftime"):
                record["Quarter"] = record["Quarter"].strftime("%Y-%m-%d")
            # Convert float32 or other numpy types
            for k, v in record.items():
                if isinstance(v, (np.float32, np.float64)):
                    record[k] = float(v)
                elif isinstance(v, (np.int32, np.int64)):
                    record[k] = int(v)
                elif pd.isna(v):
                    record[k] = None
            records.append(record)
        serializable_sim[sc_name] = records
        
    # Compile everything into a single JS export
    js_content = f"""// Auto-generated by prepare_web_dashboard_data.py
export const modelData = {{
  coefficients: {json.dumps(coef_dict, indent=2)},
  baselineSurvival: {json.dumps(baseline_survival_dict, indent=2)},
  financials: {json.dumps(financials_dict, indent=2)},
  tvs: {json.dumps(tvs_dict, indent=2)},
  banks: {json.dumps(banks_dict, indent=2)},
  exposures: {json.dumps(exposures_dict, indent=2)},
  interbank: {json.dumps(interbank_dict, indent=2)},
  historicalDefaults: {json.dumps(hist_defaults, indent=2)},
  scenarios: {json.dumps(serializable_sim, indent=2)}
}};
"""
    
    # Create target directory if it doesn't exist
    target_dir = r"C:\Users\Administrator\Desktop\CC1\dashboard\src\data"
    os.makedirs(target_dir, exist_ok=True)
    
    with open(os.path.join(target_dir, "modelData.js"), "w") as f:
        f.write(js_content)
        
    print(f"Successfully exported model parameters to {os.path.join(target_dir, 'modelData.js')}")

if __name__ == "__main__":
    main()
